### ISSUE TITLE
Enhancement request: Gallery?

### ISSUE THREAD

**Issue by dm9876** [mikahanninen/grav-plugin-facebook#15]
thanks for your work on this plugin already. It would be wonderful addition to this plugin if it also supported the facebook photo galleries.

**Comment by mikahanninen** [comment]
Sounds something that should be implemented. I will take look into it :)

**Comment by mikahanninen** [comment]
I have implemented 1st version of getting a Facebook album into Grav page. At this moment this support of getting single album from the default Facebook page (defined in the plugin). I will enhance this to support multiple albums for example.

Release number is 1.4.0

**Comment by mikahanninen** [comment]
Create new enhancement issues if and when needed.

**Comment by dm9876** [comment]
Thank you!
