### ISSUE TITLE
Request: GRAV CMS Facebook Event Importer

### ISSUE THREAD

**Issue by prinla** [mikahanninen/grav-plugin-facebook#2]
Hallo,

Sorry for disturbing you...

I've installed your Facebook-Plugin for grav-cms and I love it !!!

Now I have a special request and I don't know if you can or would like to help me:

I need to import Facebook-Events to my Grav-Website... And I have no idea how to write a grav-plugin!

But I suppose, based on your facebook-plugin for the feeds, it might be quite easy to change your plugin to work with facebook-events too

Would it be possible to help me (and probably a lot of other grav-users) to create such a plugin for facebook events?

Probably you just would have to adjust the API url, the vars and some of the values...

But I have no idea how to do this !!!

I found an interesting link about importing facebook events to a website but it requires php-include that is not possible on grav:

https://www.codeofaninja.com/2011/07/display-facebook-events-to-your-website.html

Please let me know if you are willing to help,

Thanks a lot,

Oliver

**Comment by mikahanninen** [comment]
Sorry that it took so long to answer, but I didn't notice that there are any issues (and got no notification about these).

Yes of course I can be help. I can implement this feature into this plugin also.. ?

**Comment by mikahanninen** [comment]
I investigated a bit and this seems easy to integrate into this plugin.

**Comment by prinla** [comment]
I would be sooooooo happy if you could integrate that function...

Thanks Thanks Thanks

Oliver

Visit www.Prinla.com <www.prinla.com>

_Prinla.com_
Oliver Curcuru
Tel: +34 622 197 423
Mail: info@prinla.com

**Comment by mikahanninen** [comment]
This functionality is added in the 1.2.0 version. Have fun :)
