### ISSUE TITLE
Request:

### ISSUE THREAD

**Issue by rafcontreras** [mikahanninen/grav-plugin-facebook#3]
Hi Mika, great plugin! Thank you!

Would it be possible to filter by hashtag?

**Comment by mikahanninen** [comment]
Sorry that it took so long to answer, but I didn't notice that there are any issues (and got no notification about these).

Yes I can implement that in the next version.... so the hashtags would be in the page content right ?

**Comment by mikahanninen** [comment]
This will be implemented in the v1.1.0 which I will release asap.

**Comment by rafcontreras** [comment]
Hey @mikahanninen this is awesome! Thank you very much!
