### ISSUE TITLE
About Event code : {{ facebook_events() }}

### ISSUE THREAD

**Issue by florentsyx** [mikahanninen/grav-plugin-facebook#30]
I don't know where i have to put this code !
I mean i tried to put it directly in a Grav modular page but it shows raw code on the website.
I really need help (im using gantry with the helium theme) and i have the admin panel !

**Comment by mikahanninen** [comment]
The  `{{ facebook_events() }}` is a twig function so you need to enable twig processing in your configuration.

In the Admin you can enable this is Configuration - System. There under "Content" is option "Process" which usually has only Markdown checked. Check also the "Twig".

**Comment by florentsyx** [comment]
Markdown and Twig are already checked, should i check only Twig ?

**Comment by florentsyx** [comment]
The function is actually working but it displays the code directly in the web page 
![capture](https://user-images.githubusercontent.com/29543562/27286239-b485709a-54ff-11e7-89cc-3fc517610a0e.PNG)

**Comment by mikahanninen** [comment]
I am not familiar with modular pages or Gantry. Maybe you can get answer from Slack.

**Comment by florentsyx** [comment]
Ok ill check slack then, thank you ^^

**Comment by flaviocopes** [comment]
Gantry auto-escapes the output. Just use `{{ facebook_events()|raw }}` and it should render as unescaped HTML

**Comment by florentsyx** [comment]
Thanks a lot !! You just save my life i spend a week on this function lol
