### ISSUE TITLE
Error on displaying Events

### ISSUE THREAD

**Issue by chellmann** [mikahanninen/grav-plugin-facebook#32]
Hello, 
just integrated this Plugin in a Website, displaying Posts works fine, but when i try to display Events i got a Server Error. Here is the Log:

`[2017-07-06 17:13:00] grav.CRITICAL: An exception has been thrown during the rendering of a template ("Object of class stdClass could not be converted to string") in "@Page:/webspace/03/22650/website.de/user/pages/test" at line 1. - Trace: 
#0 /webspace/03/22650/website.de/vendor/twig/twig/lib/Twig/Template.php(403): Twig_Template->displayWithErrorHandling(Array, Array) 
#1 /webspace/03/22650/website.de/vendor/twig/twig/lib/Twig/Template.php(411): Twig_Template->display(Array) 
#2 /webspace/03/22650/website.de/vendor/twig/twig/lib/Twig/Environment.php(362): Twig_Template->render(Array) 
#3 /webspace/03/22650/website.de/system/src/Grav/Common/Twig/Twig.php(246): Twig_Environment->render('@Page:/webspace...', Array) 
#4 /webspace/03/22650/website.de/system/src/Grav/Common/Page/Page.php(747): Grav\Common\Twig\Twig->processPage(Object(Grav\Common\Page\Page), '{{ facebook_eve...') 
#5 /webspace/03/22650/website.de/system/src/Grav/Common/Page/Page.php(631): Grav\Common\Page\Page->processTwig() 
#6 /webspace/03/22650/website.de/system/src/Grav/Common/Twig/Twig.php(324): Grav\Common\Page\Page->content() 
#7 /webspace/03/22650/website.de/system/src/Grav/Common/Service/OutputServiceProvider.php(19): Grav\Common\Twig\Twig->processSite('html') 
#8 /webspace/03/22650/website.de/vendor/pimple/pimple/src/Pimple/Container.php(113): Grav\Common\Service\OutputServiceProvider->Grav\Common\Service\{closure}(Object(Grav\Common\Grav)) 
#9 /webspace/03/22650/website.de/system/src/Grav/Common/Processors/RenderProcessor.php(18): Pimple\Container->offsetGet('output') 
#10 /webspace/03/22650/website.de/system/src/Grav/Common/Grav.php(126): Grav\Common\Processors\RenderProcessor->process() 
#11 /webspace/03/22650/website.de/system/src/Grav/Common/Grav.php(368): Grav\Common\Grav->Grav\Common\{closure}() 
#12 [internal function]: Grav\Common\Grav::Grav\Common\{closure}('render', 'Render', Object(Closure)) 
#13 /webspace/03/22650/website.de/system/src/Grav/Common/Grav.php(344): call_user_func_array(Object(Closure), Array) 
#14 /webspace/03/22650/website.de/system/src/Grav/Common/Grav.php(127): Grav\Common\Grav->__call('measureTime', Array) 
#15 /webspace/03/22650/website.de/index.php(52): Grav\Common\Grav->process() 
#16 {main} [] []`

**Comment by mikahanninen** [comment]
sorry about late response - how did you try to show events ? some like this ? `{{ facebook_events() }}`

**Comment by mikahanninen** [comment]
You need to enable twig processing in the page or globally.

**Comment by chellmann** [comment]
Hi! Thanks, now its working.

**Comment by mikahanninen** [comment]
Ok good 👍
