### ISSUE TITLE
Function facebook_posts in page

### ISSUE THREAD

**Issue by snzhuravlev** [mikahanninen/grav-plugin-facebook#33]
I novice in Grav.
I install Facebook plugin, next insert function in page (default) - {{ facebook_posts() }}, 
get "raw" html text in browser.
"
\<div id='facebook-posts'> <a href="https://www.facebook.com/">\<h3 class="heading">Some text\</h3></a> <div class='facebook-post'> \<a href='https://www.facebook.com/somelinks' title='Facebook post'> \<i class="fa fa-envelope post-icon" aria-hidden='true'>\</i><h4 class='media-heading'>14.08.2017 klo 08:44</h4></a> <p>
....
"

**Comment by mikahanninen** [comment]
have you enabled twig processing in the settings ?

**Comment by snzhuravlev** [comment]
yes
after add " |raw " begin better, but leave html artefacts
"
..
br /> <br /> 
...
\<figure>\<img class="media-object" src="https://scontent.xx.fbcdn.net/v/t1.0-9/s720x720/20770020_868749783289755_6057695585805911298_n.jpg?oh=6dd455c25cdc98f0c1b03041f02318a7&oe=5A1829F3">\</figure>
"
http://test.slava-yoga.com.ua/ru

function {{ facebook_events()|raw }}  - work
http://test.slava-yoga.com.ua/ru

function {{ facebook_album() }} - not
http://test.slava-yoga.com.ua/ru/foto

**Comment by mikahanninen** [comment]
I can't check this until next week - I am without computer until Monday

**Comment by snzhuravlev** [comment]
When the gantry plug-in is turned on, the Facebook plug-in does not work :(

**Comment by loopion** [comment]
I have exactly the same issue. Pretty frustrating when you see all the content in HTML but not interpreted.

**Comment by loopion** [comment]
@snzhuravlev I see that on your website you've succeed to resolve the issue. How have you resolved it for your events please?

**Comment by snzhuravlev** [comment]
@loopion I remove Gantry template and plugin

**Comment by mikahanninen** [comment]
I don't have knowledge about using this plugin with Gantry (no Gantry knowledge). Maybe ask this from maker of Gantry plugin ?

**Comment by mahagr** [comment]
@mikahanninen You need to use `|raw` filter for any output with HTML in it. Grav does not use auto-escaping by default, but Gantry forces it to turn on for improved security. This is something that will likely be forced in Grav 2.0 as well.

**Comment by mikahanninen** [comment]
Okay I will debug this issue with auto-escaping on.

**Comment by loopion** [comment]
Once I've added the `|raw` it correctly displayed the feeds except for the `<figure><img class="media-object" src="https://scontent.xx.fbcdn.net/v/t1.0-9/s720x720/21462819_1425869327448619_1429021317145976386_n.jpg?oh=08b7749481d34b678753d762f482571c&oe=5A5B012D"></figure>`

Is there a way to have this part too correctly interpreted?

Thanks @mahagr and @mikahanninen for your quick replies.

**Comment by mikahanninen** [comment]
@loopion do you have page that I view ? or can you share the page contents ?

**Comment by loopion** [comment]
Just sent you an email with it.

The album works perfectly fine, so thank you for this great plugin!

**Comment by mikahanninen** [comment]
Please tell me if release 1.6.2 fixes your problems ? I tested all functions with |raw filter and they worked.

{{ facebook_album()|raw }}
{{ facebook_posts()|raw }}
{{ facebook_events()|raw }}

**Comment by loopion** [comment]
Everything works now like a charm! Thanks a lot for this update and making it compatible with upcoming version of Grav.

Ticket can now be closed
