### ISSUE TITLE
Seriously ? Time in string format ?

### ISSUE THREAD

**Issue by Amysno** [mikahanninen/grav-plugin-facebook#34]
Hello, 

I love your plugin, it is really usefull :)
But, please, someone do something about the time data in post object... because the time is a string and not a date.....

Thanks ;)

**Comment by mikahanninen** [comment]
Time is in string format because that is shown on the page and needs to be a string. I will add 'timeObject' variable into posts for your pleasure.

**Comment by mikahanninen** [comment]
'timeObject' is now included in the Post object (release 1.6.2). Is that satisfactory ?
