### ISSUE TITLE
Day and month names in other languages than english

### ISSUE THREAD

**Issue by MacKisco** [mikahanninen/grav-plugin-facebook#37]
Hello,

I'm trying to use the plugin in my multi language website (french and english). The issue in this case with the current version is that day names and month names are only in english.

Here is my solution to retrieve other languages:
First, select "Override Locale" : Yes in Grav System Configuration.
Then replace these lines in Facebook.php:

`$start_date_array['monthName'] =
                    date('F', mktime(0, 0, 0, $start_date_array['month'], 10));
$start_date_array['dayName'] =
                    date('l', mktime(0, 0, 0, $start_date_array['month'], $start_date_array['day'],
                        $start_date_array['year']));
$end_date_array['monthName'] =
                    date('F', mktime(0, 0, 0, $end_date_array['month'], 10));`

By the following:

`$start_date_array['monthName'] = 
                    strftime ('%B', mktime(0, 0, 0, $start_date_array['month'], 10));
                $start_date_array['dayName'] = 
                    strftime ('%A', mktime(0, 0, 0, $start_date_array['month'], $start_date_array['day'], $start_date_array['year']));
                $end_date_array['monthName'] = 
                    strftime ('%B', mktime(0, 0, 0, $end_date_array['month'], 10));`

With this solution, when I switch language in my website, the day and month names also change correctly.

**Comment by mikahanninen** [comment]
I will get back to this probably on the next weekend.

**Comment by mikahanninen** [comment]
Check if release 1.7.0 works better for you.

**Comment by MacKisco** [comment]
Yes, for this issue 1.7.0 is fine, thank you
