### ISSUE TITLE
Update throws error messages

### ISSUE THREAD

**Issue by prinla** [mikahanninen/grav-plugin-facebook#9]
Thanks a lot for your update and the implementation of the facebook-events...

But unfortunately after updating I got error messages in both possibilities:

{{ facebook_posts() }} gives this error:
"0 - An exception has been thrown during the rendering of a template ("krsort() expects parameter 1 to be array, null given") in "modular/news.html.twig" at line 10."
{{ facebook_events() }} gives this error:
"0 - An exception has been thrown during the rendering of a template ("Undefined property: stdClass::$end_time") in "modular/news.html.twig" at line 10."

For the moment I disabled the plugin...
But if you want access to my site or more details about it just tell me...
Hope we'll find a quick solution...

Thanks for all your help

**Comment by mikahanninen** [comment]
The 1.2.0 update was unfortunately such that after it is installed, all the configuration must be reset. Did you do that ? I will try to reproduce the errors you have mentioned. 

I think I know the error in facebook_events() but at the moment I am not sure what causes the first error. 

Details and/or access to your site could help alot.

**Comment by mikahanninen** [comment]
I have created release 1.2.2. Please tell me if that fixes the errors above.

**Comment by prinla** [comment]
It's working perfectly now !!! I don't know you personally, but right now I would say "YOU ARE GREAT" :)
Thanks so much... 
- For your information, yes, I did change the configuration after the first update. (The new Update doesn't need a re-configuration - great!)
- Do you think there is a way to also implement the "Event picture" and a link to the event
- This is a very powerful plugin for facebook implementation into grav, would you mind if I continue thinking about how to improve it in the future ?
- If so maybe better to not communicate only here in the issue-folder of github... I could send you messages to your email "mika.hanninen@gmail.com" or any other if you prefer. Mine is info@prinla.com
- For your information the website I work on right now and where your plugin is used is "test5.prinla.com"... I could send you access if needed by private mail.

Another big thank you for your great cooperation

**Comment by mikahanninen** [comment]
Glad that problems are gone for you :) I will close this issue and we can continue communicating through emails.
